Agregué mi nombre 30-3-2023
JuanCarlosPlata/Hyperblog pull request #26
Opened 2023-03-30 18:03 UTC by carloszch

2023-03-31 09:21 UTC, JuanCarlosPlata requested changes
compañero en la linea 39 y 49 coloco la palabra main, la cual no cumple ninguna función, por favor corregir los errores y volver a enviar la petición de merge

2023-03-31 09:26 UTC, JuanCarlosPlata commented
puede simplemente borrar este push request y aplicar los cambios en su repositorio y volver a enviar el push request.

2023-04-03 10:43 UTC, JuanCarlosPlata commented
como vi que no respondía le solucione los conflictos que tenia, y deberá actualizar sus rama para que este al día con los cambios actuales.

2023-04-03 10:43 UTC, merged

2023-05-14 10:10 UTC, carloszch commented
Hola, muchas gracias, voy a revisar que fue lo que hice mal. Estoy empezando con esto de la tecnología y tengo mucho que aprender, pero estoy muy contento de tener esta oportunidad.
Dios lo bendiga.

2023-05-14 19:28 UTC, JuanCarlosPlata commented
Hola no hizo nada malo, solo que habían varios pulls request antes y respondí otros y por eso el tuyo quedaba desactualizado, yo le dije que lo volviera a actualizarlos pues si están desactualizados no deja hacer el pull request, pero yo modifique el cambio y quedó solucionando

2023-05-14 20:30 UTC, carloszch commented
Hola. Ok pura vida. Ya casi termino el curso de Git y GitHub. Es algo muy
amplio pero me ha servido mucho pues también estoy llevando HTML y css, y
lo he usado para subir a GitHub lo que voy aprendiendo.

No tengo muy claro aun como se solucionan los conflictos pero lo voy a
estudiar más a fondo.

Gracias Juan Carlos. Es bueno saber que te puedo consultar si salen dudas
en el camino.

El dom., 14 may. 2023 1:29 p. m., Juan Carlos Plata Prada <
***@***.***> escribió:

> Hola no hizo nada malo, solo que habían varios pulls request antes y
> respondí otros y por eso el tuyo quedaba desactualizado, yo le dije que lo
> volviera a actualizarlos pues si están desactualizados no deja hacer el
> pull request, pero yo modifique el cambio y quedó solucionando
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JuanCarlosPlata/Hyperblog/pull/26#issuecomment-1546982672>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4WRG2LPH5TLPF5RIFR6ML3XGEW7XANCNFSM6AAAAAAWNUMOT4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>